# Generated by Django 6.0.4 on 2026-05-02 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='batch',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_encrypted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time_gated_until',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='busroute',
            name='current_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='status',
            field=models.CharField(default='On Time', max_length=20),
        ),
        migrations.AddField(
            model_name='busroute',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='DefaultRoll', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Chancellor', 'Chancellor'), ('ViceChancellor', 'Vice Chancellor'), ('Dean', 'Dean'), ('Registrar', 'Registrar'), ('HoD', 'Head of Department'), ('CoE', 'Controller of Examinations'), ('Finance', 'Finance Officer'), ('PlacementOfficer', 'Placement Officer'), ('Faculty', 'Faculty'), ('Admin', 'Administrator'), ('Staff', 'Administrative Staff'), ('Student', 'Student'), ('Parent', 'Parent')], max_length=30),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_role', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('hours_per_week', models.IntegerField(default=3)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('max_hours_per_day', models.IntegerField(default=6)),
                ('assigned_batches', models.JSONField(default=list)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(related_name='teachers', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('total_marks', models.IntegerField(default=100)),
                ('submissions', models.IntegerField(default=0)),
                ('batch', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('absent_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_subs', to=settings.AUTH_USER_MODEL)),
                ('substitute_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covering_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('slot', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('is_optimized', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
    ]
