# Generated by Django 6.0.6 on 2026-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_content_message_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTabMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('tab_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(default='Base Portal', max_length=100)),
            ],
            options={
                'ordering': ['role', 'category', 'order'],
                'unique_together': {('role', 'tab_id')},
            },
        ),
    ]
